#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXParticlesEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* Window1;
	ISXGUIToolBar* ToolBar1;
	ISXGUIListBox* ListBox1;
	ISXGUIListBox* ListBox2;
	ISXGUIStatic* Static1;
	ISXGUIButton* Button1;
	ISXGUIStatic* Static2;
	ISXGUIButton* Button2;
	ISXGUIButton* Button3;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIButton* Button10;
	ISXGUIButton* Button11;
	ISXGUIButton* Button12;
	ISXGUIButton* Button13;
	ISXGUIStatic* StaticSpawnPosType;
	ISXGUIComboBox* ComboBoxSpawnPosType;
	ISXGUIStatic* StaticSpawnOrigin;
	ISXGUIStatic* StaticSpawnOriginX;
	ISXGUIEdit* EditSpawnOriginX;
	ISXGUIStatic* StaticSpawnOriginY;
	ISXGUIEdit* EditSpawnOriginY;
	ISXGUIStatic* StaticSpawnOriginZ;
	ISXGUIEdit* EditSpawnOriginZ;
	ISXGUIStatic* StaticSpawnOriginDisp;
	ISXGUIEdit* EditSpawnOriginDisp;
	ISXGUICheckBox* CheckBoxSpawnOriginDispXPos;
	ISXGUICheckBox* CheckBoxSpawnOriginDispXNeg;
	ISXGUICheckBox* CheckBoxSpawnOriginDispYPos;
	ISXGUICheckBox* CheckBoxSpawnOriginDispYNeg;
	ISXGUICheckBox* CheckBoxSpawnOriginDispZPos;
	ISXGUICheckBox* CheckBoxSpawnOriginDispZNeg;
	ISXGUIStatic* StaticSpawnNextTime;
	ISXGUIEdit* EditSpawnNextTime;
	ISXGUIStatic* StaticSpawnNextTimeDisp;
	ISXGUIEdit* EditSpawnNextTimeDisp;

	void InitAllElements();

	void DeleteAllElements();

};

void SXParticlesEditor::InitAllElements()
{
	SXParticlesEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,237,74,820,650,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXParticlesEditor::JobWindow);

	SXParticlesEditor::Window1 = SXGUICrBaseWnd("Window1","Window1",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXParticlesEditor::JobWindow->GetHWND(),0);
	SXParticlesEditor::ToolBar1 = SXGUICrToolBar("",0,1,804,24,804,24,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ListBox1 = SXGUICrListBox("",602,50,200,145,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox1->SetColorText(0,0,0);
	SXParticlesEditor::ListBox1->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox1->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox1->SetColorBrush(255,255,255);
	SXParticlesEditor::ListBox2 = SXGUICrListBox("",602,300,200,54,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox2->SetColorText(0,0,0);
	SXParticlesEditor::ListBox2->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox2->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox2->SetColorBrush(255,255,255);
	SXParticlesEditor::Static1 = SXGUICrStatic("Effects:",610,30,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static1->SetColorText(0,0,0);
	SXParticlesEditor::Static1->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static1->SetTransparentTextBk(true);
	SXParticlesEditor::Static1->SetColorBrush(220,220,220);
	SXParticlesEditor::Button1 = SXGUICrButton("Create",605,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2 = SXGUICrStatic("Particles:",610,275,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2->SetColorText(0,0,0);
	SXParticlesEditor::Static2->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static2->SetTransparentTextBk(true);
	SXParticlesEditor::Static2->SetColorBrush(220,220,220);
	SXParticlesEditor::Button2 = SXGUICrButton("Edit",670,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button3 = SXGUICrButton("Delete",735,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button4 = SXGUICrButton("Create",605,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button5 = SXGUICrButton("Edit",670,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button6 = SXGUICrButton("Delete",735,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button7 = SXGUICrButton("Base",25,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button8 = SXGUICrButton("TextureAnimTex",130,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button9 = SXGUICrButton("Spawn",235,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button10 = SXGUICrButton("Bound",340,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button10->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button11 = SXGUICrButton("Graphics",665,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button11->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button12 = SXGUICrButton("Charaters",560,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button12->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button13 = SXGUICrButton("VelocityAcceleration",445,434,110,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button13->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnPosType = SXGUICrStatic("SpawnPosType:",5,462,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnPosType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnPosType->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnPosType->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnPosType->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnPosType->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxSpawnPosType = SXGUICrComboBox("",90,460,140,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxSpawnPosType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxSpawnPosType->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxSpawnPosType->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxSpawnPosType->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxSpawnPosType->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSpawnOrigin = SXGUICrStatic("SpawnOrigin:",5,490,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnOrigin->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnOrigin->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnOrigin->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnOrigin->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnOrigin->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticSpawnOriginX = SXGUICrStatic("x:",90,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnOriginX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnOriginX->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnOriginX->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnOriginX->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnOriginX->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnOriginX = SXGUICrEdit("0",100,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnOriginX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnOriginX->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnOriginX->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnOriginX->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnOriginX->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSpawnOriginY = SXGUICrStatic("y:",180,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnOriginY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnOriginY->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnOriginY->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnOriginY->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnOriginY->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnOriginY = SXGUICrEdit("0",190,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnOriginY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnOriginY->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnOriginY->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnOriginY->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnOriginY->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSpawnOriginZ = SXGUICrStatic("z:",270,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnOriginZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnOriginZ->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnOriginZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnOriginZ->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnOriginZ->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnOriginZ = SXGUICrEdit("0",280,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnOriginZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnOriginZ->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnOriginZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnOriginZ->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnOriginZ->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSpawnOriginDisp = SXGUICrStatic("SpawnOriginDisp:",370,490,85,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnOriginDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnOriginDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnOriginDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnOriginDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnOriginDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnOriginDisp = SXGUICrEdit("0",455,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnOriginDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnOriginDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnOriginDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnOriginDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnOriginDisp->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos = SXGUICrCheckBox("x+",90,510,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispXPos->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg = SXGUICrCheckBox("x-",140,510,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispXNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos = SXGUICrCheckBox("y+",180,510,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispYPos->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg = SXGUICrCheckBox("y-",230,510,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispYNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos = SXGUICrCheckBox("z+",270,510,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispZPos->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg = SXGUICrCheckBox("z-",320,509,30,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxSpawnOriginDispZNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticSpawnNextTime = SXGUICrStatic("SpawnNextTime:",5,540,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnNextTime->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnNextTime->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnNextTime->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnNextTime->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnNextTime->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnNextTime = SXGUICrEdit("0",90,540,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnNextTime->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnNextTime->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnNextTime->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnNextTime->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnNextTime->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSpawnNextTimeDisp = SXGUICrStatic("SpawnNextTimeDisp:",175,540,105,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSpawnNextTimeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSpawnNextTimeDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticSpawnNextTimeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSpawnNextTimeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSpawnNextTimeDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSpawnNextTimeDisp = SXGUICrEdit("0",280,540,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSpawnNextTimeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSpawnNextTimeDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditSpawnNextTimeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSpawnNextTimeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditSpawnNextTimeDisp->SetColorBrush(255,255,255);
}
void SXParticlesEditor::DeleteAllElements()
{
	mem_delete(SXParticlesEditor::Window1);
	mem_delete(SXParticlesEditor::ToolBar1);
	mem_delete(SXParticlesEditor::ListBox1);
	mem_delete(SXParticlesEditor::ListBox2);
	mem_delete(SXParticlesEditor::Static1);
	mem_delete(SXParticlesEditor::Button1);
	mem_delete(SXParticlesEditor::Static2);
	mem_delete(SXParticlesEditor::Button2);
	mem_delete(SXParticlesEditor::Button3);
	mem_delete(SXParticlesEditor::Button4);
	mem_delete(SXParticlesEditor::Button5);
	mem_delete(SXParticlesEditor::Button6);
	mem_delete(SXParticlesEditor::Button7);
	mem_delete(SXParticlesEditor::Button8);
	mem_delete(SXParticlesEditor::Button9);
	mem_delete(SXParticlesEditor::Button10);
	mem_delete(SXParticlesEditor::Button11);
	mem_delete(SXParticlesEditor::Button12);
	mem_delete(SXParticlesEditor::Button13);
	mem_delete(SXParticlesEditor::StaticSpawnPosType);
	mem_delete(SXParticlesEditor::ComboBoxSpawnPosType);
	mem_delete(SXParticlesEditor::StaticSpawnOrigin);
	mem_delete(SXParticlesEditor::StaticSpawnOriginX);
	mem_delete(SXParticlesEditor::EditSpawnOriginX);
	mem_delete(SXParticlesEditor::StaticSpawnOriginY);
	mem_delete(SXParticlesEditor::EditSpawnOriginY);
	mem_delete(SXParticlesEditor::StaticSpawnOriginZ);
	mem_delete(SXParticlesEditor::EditSpawnOriginZ);
	mem_delete(SXParticlesEditor::StaticSpawnOriginDisp);
	mem_delete(SXParticlesEditor::EditSpawnOriginDisp);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispXPos);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispXNeg);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispYPos);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispYNeg);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispZPos);
	mem_delete(SXParticlesEditor::CheckBoxSpawnOriginDispZNeg);
	mem_delete(SXParticlesEditor::StaticSpawnNextTime);
	mem_delete(SXParticlesEditor::EditSpawnNextTime);
	mem_delete(SXParticlesEditor::StaticSpawnNextTimeDisp);
	mem_delete(SXParticlesEditor::EditSpawnNextTimeDisp);
	mem_delete(SXParticlesEditor::JobWindow);
}
