#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXParticlesEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* Window1;
	ISXGUIToolBar* ToolBar1;
	ISXGUIListBox* ListBox1;
	ISXGUIListBox* ListBox2;
	ISXGUIStatic* Static1;
	ISXGUIButton* Button1;
	ISXGUIStatic* Static2;
	ISXGUIButton* Button2;
	ISXGUIButton* Button3;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIButton* Button10;
	ISXGUIButton* Button11;
	ISXGUIButton* Button12;
	ISXGUIButton* Button13;
	ISXGUICheckBox* CheckBoxCircle;
	ISXGUIStatic* StaticCircleAxis;
	ISXGUIComboBox* ComboBoxCircleAxis;
	ISXGUIStatic* StaticCircleAngle;
	ISXGUIEdit* EditCircleAngle;
	ISXGUIStatic* StaticCircleAngleDisp;
	ISXGUIEdit* EditCircleAngleDisp;
	ISXGUICheckBox* CheckBoxRotate;
	ISXGUIStatic* StaticRotateAngle;
	ISXGUIEdit* EditRotateAngle;
	ISXGUIStatic* StaticRotateAngleDisp;
	ISXGUICheckBox* CheckBoxCircleAngleDispNeg;
	ISXGUIEdit* EditCircleAngleDispNeg;
	ISXGUICheckBox* CheckBoxRotateAngleDispNeg;
	ISXGUICheckBox* CheckBoxDeviation;
	ISXGUIStatic* StaticDeviationType;
	ISXGUIComboBox* ComboBoxDeviationType;
	ISXGUIStatic* StaticDeviationAmplitude;
	ISXGUIStatic* StaticDeviationCoefAngle;
	ISXGUIEdit* EditDeviationAmplitude;
	ISXGUIEdit* EditDeviationCoefAngle;
	ISXGUIStatic* StaticDeviationAxis;
	ISXGUIComboBox* ComboBoxDeviationAxis;
	ISXGUIStatic* StaticDeviationCountDelayMls;
	ISXGUIEdit* EditDeviationCountDelayMls;
	ISXGUIStatic* StaticDeviationCoefAngleDisp;
	ISXGUIEdit* EditDeviationCoefAngleDisp;
	ISXGUICheckBox* CheckBoxDeviationCoefAngleDispNeg;
	ISXGUICheckBox* CheckBoxDeviationTapX;
	ISXGUICheckBox* CheckBoxDeviationTapY;
	ISXGUICheckBox* CheckBoxDeviationTapZ;

	void InitAllElements();

	void DeleteAllElements();

};

void SXParticlesEditor::InitAllElements()
{
	SXParticlesEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,235,74,820,650,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXParticlesEditor::JobWindow);

	SXParticlesEditor::Window1 = SXGUICrBaseWnd("Window1","Window1",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXParticlesEditor::JobWindow->GetHWND(),0);
	SXParticlesEditor::ToolBar1 = SXGUICrToolBar("",0,1,804,24,804,24,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ListBox1 = SXGUICrListBox("",602,50,200,119,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox1->SetColorText(0,0,0);
	SXParticlesEditor::ListBox1->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox1->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox1->SetColorBrush(255,255,255);
	SXParticlesEditor::ListBox2 = SXGUICrListBox("",602,300,200,41,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox2->SetColorText(0,0,0);
	SXParticlesEditor::ListBox2->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox2->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox2->SetColorBrush(255,255,255);
	SXParticlesEditor::Static1 = SXGUICrStatic("Effects:",610,30,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static1->SetColorText(0,0,0);
	SXParticlesEditor::Static1->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static1->SetTransparentTextBk(true);
	SXParticlesEditor::Static1->SetColorBrush(220,220,220);
	SXParticlesEditor::Button1 = SXGUICrButton("Create",605,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2 = SXGUICrStatic("Particles:",610,275,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2->SetColorText(0,0,0);
	SXParticlesEditor::Static2->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static2->SetTransparentTextBk(true);
	SXParticlesEditor::Static2->SetColorBrush(220,220,220);
	SXParticlesEditor::Button2 = SXGUICrButton("Edit",670,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button3 = SXGUICrButton("Delete",735,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button4 = SXGUICrButton("Create",605,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button5 = SXGUICrButton("Edit",670,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button6 = SXGUICrButton("Delete",735,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button7 = SXGUICrButton("Base",25,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button8 = SXGUICrButton("TextureAnimTex",130,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button9 = SXGUICrButton("Spawn",235,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button10 = SXGUICrButton("Bound",340,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button10->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button11 = SXGUICrButton("Graphics",665,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button11->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button12 = SXGUICrButton("Charaters",560,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button12->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button13 = SXGUICrButton("VelocityAcceleration",445,434,110,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button13->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxCircle = SXGUICrCheckBox("Circle",5,460,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxCircle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxCircle->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxCircle->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxCircle->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxCircle->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticCircleAxis = SXGUICrStatic("CircleAxis:",5,482,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticCircleAxis->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticCircleAxis->SetColorText(0,0,0);
	SXParticlesEditor::StaticCircleAxis->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticCircleAxis->SetTransparentTextBk(true);
	SXParticlesEditor::StaticCircleAxis->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxCircleAxis = SXGUICrComboBox("",60,480,100,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxCircleAxis->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxCircleAxis->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxCircleAxis->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxCircleAxis->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxCircleAxis->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticCircleAngle = SXGUICrStatic("CircleAngle:",5,505,60,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticCircleAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticCircleAngle->SetColorText(0,0,0);
	SXParticlesEditor::StaticCircleAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticCircleAngle->SetTransparentTextBk(true);
	SXParticlesEditor::StaticCircleAngle->SetColorBrush(220,220,220);
	SXParticlesEditor::EditCircleAngle = SXGUICrEdit("0",90,505,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditCircleAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditCircleAngle->SetColorText(0,0,0);
	SXParticlesEditor::EditCircleAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditCircleAngle->SetTransparentTextBk(true);
	SXParticlesEditor::EditCircleAngle->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticCircleAngleDisp = SXGUICrStatic("CircleAngleDisp:",6,525,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticCircleAngleDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticCircleAngleDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticCircleAngleDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticCircleAngleDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticCircleAngleDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditCircleAngleDisp = SXGUICrEdit("0",90,525,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditCircleAngleDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditCircleAngleDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditCircleAngleDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditCircleAngleDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditCircleAngleDisp->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxRotate = SXGUICrCheckBox("Rotate",175,460,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxRotate->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxRotate->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxRotate->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxRotate->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxRotate->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticRotateAngle = SXGUICrStatic("RotateAngle:",175,480,85,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticRotateAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticRotateAngle->SetColorText(0,0,0);
	SXParticlesEditor::StaticRotateAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticRotateAngle->SetTransparentTextBk(true);
	SXParticlesEditor::StaticRotateAngle->SetColorBrush(220,220,220);
	SXParticlesEditor::EditRotateAngle = SXGUICrEdit("0",265,480,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditRotateAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditRotateAngle->SetColorText(0,0,0);
	SXParticlesEditor::EditRotateAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditRotateAngle->SetTransparentTextBk(true);
	SXParticlesEditor::EditRotateAngle->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticRotateAngleDisp = SXGUICrStatic("RotateAngleDisp:",175,500,85,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticRotateAngleDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticRotateAngleDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticRotateAngleDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticRotateAngleDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticRotateAngleDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg = SXGUICrCheckBox("CircleAngleDispNeg",5,545,120,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxCircleAngleDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::EditCircleAngleDispNeg = SXGUICrEdit("0",265,500,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditCircleAngleDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditCircleAngleDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::EditCircleAngleDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditCircleAngleDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::EditCircleAngleDispNeg->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg = SXGUICrCheckBox("RotateAngleDispNeg",175,520,120,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxRotateAngleDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxDeviation = SXGUICrCheckBox("Deviation",350,460,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxDeviation->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxDeviation->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxDeviation->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxDeviation->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxDeviation->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticDeviationType = SXGUICrStatic("DeviationType:",350,480,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationType->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationType->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationType->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationType->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxDeviationType = SXGUICrComboBox("",455,475,130,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxDeviationType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxDeviationType->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxDeviationType->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxDeviationType->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxDeviationType->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticDeviationAmplitude = SXGUICrStatic("DeviationAmplitude:",350,500,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationAmplitude->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationAmplitude->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationAmplitude->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationAmplitude->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationAmplitude->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticDeviationCoefAngle = SXGUICrStatic("DeviationCoefAngle:",350,520,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationCoefAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationCoefAngle->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationCoefAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationCoefAngle->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationCoefAngle->SetColorBrush(220,220,220);
	SXParticlesEditor::EditDeviationAmplitude = SXGUICrEdit("0",490,500,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditDeviationAmplitude->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditDeviationAmplitude->SetColorText(0,0,0);
	SXParticlesEditor::EditDeviationAmplitude->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditDeviationAmplitude->SetTransparentTextBk(true);
	SXParticlesEditor::EditDeviationAmplitude->SetColorBrush(255,255,255);
	SXParticlesEditor::EditDeviationCoefAngle = SXGUICrEdit("0",490,520,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditDeviationCoefAngle->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditDeviationCoefAngle->SetColorText(0,0,0);
	SXParticlesEditor::EditDeviationCoefAngle->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditDeviationCoefAngle->SetTransparentTextBk(true);
	SXParticlesEditor::EditDeviationCoefAngle->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticDeviationAxis = SXGUICrStatic("DeviationAxis:",590,475,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationAxis->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationAxis->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationAxis->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationAxis->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationAxis->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxDeviationAxis = SXGUICrComboBox("",675,470,130,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxDeviationAxis->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxDeviationAxis->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxDeviationAxis->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxDeviationAxis->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxDeviationAxis->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticDeviationCountDelayMls = SXGUICrStatic("DeviationCountDelayMls:",590,495,120,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationCountDelayMls->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationCountDelayMls->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationCountDelayMls->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationCountDelayMls->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationCountDelayMls->SetColorBrush(220,220,220);
	SXParticlesEditor::EditDeviationCountDelayMls = SXGUICrEdit("0",715,495,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditDeviationCountDelayMls->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditDeviationCountDelayMls->SetColorText(0,0,0);
	SXParticlesEditor::EditDeviationCountDelayMls->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditDeviationCountDelayMls->SetTransparentTextBk(true);
	SXParticlesEditor::EditDeviationCountDelayMls->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticDeviationCoefAngleDisp = SXGUICrStatic("DeviationCoefAngleDisp:",350,540,120,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDeviationCoefAngleDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDeviationCoefAngleDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticDeviationCoefAngleDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDeviationCoefAngleDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDeviationCoefAngleDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditDeviationCoefAngleDisp = SXGUICrEdit("0",490,540,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditDeviationCoefAngleDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditDeviationCoefAngleDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditDeviationCoefAngleDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditDeviationCoefAngleDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditDeviationCoefAngleDisp->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg = SXGUICrCheckBox("DeviationCoefAngleDispNeg",350,560,160,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxDeviationTapX = SXGUICrCheckBox("DeviationTapX",590,515,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxDeviationTapX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapX->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapX->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxDeviationTapX->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxDeviationTapX->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxDeviationTapY = SXGUICrCheckBox("DeviationTapY",590,535,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxDeviationTapY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapY->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapY->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxDeviationTapY->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxDeviationTapY->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxDeviationTapZ = SXGUICrCheckBox("DeviationTapZ",590,555,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxDeviationTapZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapZ->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxDeviationTapZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxDeviationTapZ->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxDeviationTapZ->SetColorBrush(220,220,220);
}
void SXParticlesEditor::DeleteAllElements()
{
	mem_delete(SXParticlesEditor::Window1);
	mem_delete(SXParticlesEditor::ToolBar1);
	mem_delete(SXParticlesEditor::ListBox1);
	mem_delete(SXParticlesEditor::ListBox2);
	mem_delete(SXParticlesEditor::Static1);
	mem_delete(SXParticlesEditor::Button1);
	mem_delete(SXParticlesEditor::Static2);
	mem_delete(SXParticlesEditor::Button2);
	mem_delete(SXParticlesEditor::Button3);
	mem_delete(SXParticlesEditor::Button4);
	mem_delete(SXParticlesEditor::Button5);
	mem_delete(SXParticlesEditor::Button6);
	mem_delete(SXParticlesEditor::Button7);
	mem_delete(SXParticlesEditor::Button8);
	mem_delete(SXParticlesEditor::Button9);
	mem_delete(SXParticlesEditor::Button10);
	mem_delete(SXParticlesEditor::Button11);
	mem_delete(SXParticlesEditor::Button12);
	mem_delete(SXParticlesEditor::Button13);
	mem_delete(SXParticlesEditor::CheckBoxCircle);
	mem_delete(SXParticlesEditor::StaticCircleAxis);
	mem_delete(SXParticlesEditor::ComboBoxCircleAxis);
	mem_delete(SXParticlesEditor::StaticCircleAngle);
	mem_delete(SXParticlesEditor::EditCircleAngle);
	mem_delete(SXParticlesEditor::StaticCircleAngleDisp);
	mem_delete(SXParticlesEditor::EditCircleAngleDisp);
	mem_delete(SXParticlesEditor::CheckBoxRotate);
	mem_delete(SXParticlesEditor::StaticRotateAngle);
	mem_delete(SXParticlesEditor::EditRotateAngle);
	mem_delete(SXParticlesEditor::StaticRotateAngleDisp);
	mem_delete(SXParticlesEditor::CheckBoxCircleAngleDispNeg);
	mem_delete(SXParticlesEditor::EditCircleAngleDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxRotateAngleDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxDeviation);
	mem_delete(SXParticlesEditor::StaticDeviationType);
	mem_delete(SXParticlesEditor::ComboBoxDeviationType);
	mem_delete(SXParticlesEditor::StaticDeviationAmplitude);
	mem_delete(SXParticlesEditor::StaticDeviationCoefAngle);
	mem_delete(SXParticlesEditor::EditDeviationAmplitude);
	mem_delete(SXParticlesEditor::EditDeviationCoefAngle);
	mem_delete(SXParticlesEditor::StaticDeviationAxis);
	mem_delete(SXParticlesEditor::ComboBoxDeviationAxis);
	mem_delete(SXParticlesEditor::StaticDeviationCountDelayMls);
	mem_delete(SXParticlesEditor::EditDeviationCountDelayMls);
	mem_delete(SXParticlesEditor::StaticDeviationCoefAngleDisp);
	mem_delete(SXParticlesEditor::EditDeviationCoefAngleDisp);
	mem_delete(SXParticlesEditor::CheckBoxDeviationCoefAngleDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxDeviationTapX);
	mem_delete(SXParticlesEditor::CheckBoxDeviationTapY);
	mem_delete(SXParticlesEditor::CheckBoxDeviationTapZ);
	mem_delete(SXParticlesEditor::JobWindow);
}
