#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXParticlesEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* Window1;
	ISXGUIToolBar* ToolBar1;
	ISXGUIListBox* ListBox1;
	ISXGUIListBox* ListBox2;
	ISXGUIStatic* Static1;
	ISXGUIButton* Button1;
	ISXGUIStatic* Static2;
	ISXGUIButton* Button2;
	ISXGUIButton* Button3;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIButton* Button10;
	ISXGUIButton* Button11;
	ISXGUIButton* Button12;
	ISXGUIButton* Button13;
	ISXGUIStatic* StaticBoundType;
	ISXGUIComboBox* ComboBoxBoundType;
	ISXGUIStatic* StaticVector1;
	ISXGUIStatic* StaticVec1X;
	ISXGUIEdit* EditVec1X;
	ISXGUIStatic* StaticVec1Y;
	ISXGUIEdit* EditVec1Y;
	ISXGUIStatic* StaticVec1Z;
	ISXGUIEdit* EditVec1Z;
	ISXGUIStatic* StaticVec1W;
	ISXGUIEdit* EditVec1W;
	ISXGUIStatic* StaticVector2;
	ISXGUIStatic* StaticVec2X;
	ISXGUIEdit* EditVec2X;
	ISXGUIStatic* StaticVec2Y;
	ISXGUIEdit* EditVec2Y;
	ISXGUIStatic* StaticVec2Z;
	ISXGUIEdit* EditVec2Z;
	ISXGUIStatic* StaticVec2W;
	ISXGUIEdit* EditVec2W;

	void InitAllElements();

	void DeleteAllElements();

};

void SXParticlesEditor::InitAllElements()
{
	SXParticlesEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,237,74,820,650,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXParticlesEditor::JobWindow);

	SXParticlesEditor::Window1 = SXGUICrBaseWnd("Window1","Window1",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXParticlesEditor::JobWindow->GetHWND(),0);
	SXParticlesEditor::ToolBar1 = SXGUICrToolBar("",0,1,804,24,804,24,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ListBox1 = SXGUICrListBox("",602,50,200,145,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox1->SetColorText(0,0,0);
	SXParticlesEditor::ListBox1->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox1->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox1->SetColorBrush(255,255,255);
	SXParticlesEditor::ListBox2 = SXGUICrListBox("",602,300,200,54,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox2->SetColorText(0,0,0);
	SXParticlesEditor::ListBox2->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox2->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox2->SetColorBrush(255,255,255);
	SXParticlesEditor::Static1 = SXGUICrStatic("Effects:",610,30,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static1->SetColorText(0,0,0);
	SXParticlesEditor::Static1->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static1->SetTransparentTextBk(true);
	SXParticlesEditor::Static1->SetColorBrush(220,220,220);
	SXParticlesEditor::Button1 = SXGUICrButton("Create",605,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2 = SXGUICrStatic("Particles:",610,275,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2->SetColorText(0,0,0);
	SXParticlesEditor::Static2->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static2->SetTransparentTextBk(true);
	SXParticlesEditor::Static2->SetColorBrush(220,220,220);
	SXParticlesEditor::Button2 = SXGUICrButton("Edit",670,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button3 = SXGUICrButton("Delete",735,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button4 = SXGUICrButton("Create",605,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button5 = SXGUICrButton("Edit",670,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button6 = SXGUICrButton("Delete",735,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button7 = SXGUICrButton("Base",25,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button8 = SXGUICrButton("TextureAnimTex",130,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button9 = SXGUICrButton("Spawn",235,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button10 = SXGUICrButton("Bound",340,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button10->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button11 = SXGUICrButton("Graphics",665,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button11->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button12 = SXGUICrButton("Charaters",560,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button12->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button13 = SXGUICrButton("VelocityAcceleration",445,434,110,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button13->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticBoundType = SXGUICrStatic("Bound type:",5,462,60,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticBoundType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticBoundType->SetColorText(0,0,0);
	SXParticlesEditor::StaticBoundType->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticBoundType->SetTransparentTextBk(true);
	SXParticlesEditor::StaticBoundType->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxBoundType = SXGUICrComboBox("",80,460,140,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxBoundType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxBoundType->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxBoundType->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxBoundType->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxBoundType->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVector1 = SXGUICrStatic("Vector1:",5,490,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVector1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVector1->SetColorText(0,0,0);
	SXParticlesEditor::StaticVector1->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVector1->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVector1->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticVec1X = SXGUICrStatic("x:",60,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec1X->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec1X->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec1X->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec1X->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec1X->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec1X = SXGUICrEdit("0",70,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec1X->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec1X->SetColorText(0,0,0);
	SXParticlesEditor::EditVec1X->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec1X->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec1X->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec1Y = SXGUICrStatic("y:",150,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec1Y->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec1Y->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec1Y->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec1Y->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec1Y->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec1Y = SXGUICrEdit("0",160,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec1Y->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec1Y->SetColorText(0,0,0);
	SXParticlesEditor::EditVec1Y->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec1Y->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec1Y->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec1Z = SXGUICrStatic("z:",235,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec1Z->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec1Z->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec1Z->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec1Z->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec1Z->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec1Z = SXGUICrEdit("0",245,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec1Z->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec1Z->SetColorText(0,0,0);
	SXParticlesEditor::EditVec1Z->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec1Z->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec1Z->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec1W = SXGUICrStatic("w:",320,490,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec1W->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec1W->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec1W->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec1W->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec1W->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec1W = SXGUICrEdit("0",330,490,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec1W->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec1W->SetColorText(0,0,0);
	SXParticlesEditor::EditVec1W->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec1W->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec1W->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVector2 = SXGUICrStatic("Vector2:",5,510,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVector2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVector2->SetColorText(0,0,0);
	SXParticlesEditor::StaticVector2->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVector2->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVector2->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticVec2X = SXGUICrStatic("x:",60,510,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec2X->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec2X->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec2X->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec2X->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec2X->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec2X = SXGUICrEdit("0",70,510,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec2X->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec2X->SetColorText(0,0,0);
	SXParticlesEditor::EditVec2X->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec2X->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec2X->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec2Y = SXGUICrStatic("y:",150,510,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec2Y->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec2Y->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec2Y->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec2Y->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec2Y->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec2Y = SXGUICrEdit("0",160,510,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec2Y->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec2Y->SetColorText(0,0,0);
	SXParticlesEditor::EditVec2Y->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec2Y->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec2Y->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec2Z = SXGUICrStatic("z:",235,510,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec2Z->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec2Z->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec2Z->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec2Z->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec2Z->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec2Z = SXGUICrEdit("0",245,510,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec2Z->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec2Z->SetColorText(0,0,0);
	SXParticlesEditor::EditVec2Z->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec2Z->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec2Z->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticVec2W = SXGUICrStatic("w:",320,510,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVec2W->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVec2W->SetColorText(0,0,0);
	SXParticlesEditor::StaticVec2W->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVec2W->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVec2W->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVec2W = SXGUICrEdit("0",330,510,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVec2W->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVec2W->SetColorText(0,0,0);
	SXParticlesEditor::EditVec2W->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVec2W->SetTransparentTextBk(true);
	SXParticlesEditor::EditVec2W->SetColorBrush(255,255,255);
}
void SXParticlesEditor::DeleteAllElements()
{
	mem_delete(SXParticlesEditor::Window1);
	mem_delete(SXParticlesEditor::ToolBar1);
	mem_delete(SXParticlesEditor::ListBox1);
	mem_delete(SXParticlesEditor::ListBox2);
	mem_delete(SXParticlesEditor::Static1);
	mem_delete(SXParticlesEditor::Button1);
	mem_delete(SXParticlesEditor::Static2);
	mem_delete(SXParticlesEditor::Button2);
	mem_delete(SXParticlesEditor::Button3);
	mem_delete(SXParticlesEditor::Button4);
	mem_delete(SXParticlesEditor::Button5);
	mem_delete(SXParticlesEditor::Button6);
	mem_delete(SXParticlesEditor::Button7);
	mem_delete(SXParticlesEditor::Button8);
	mem_delete(SXParticlesEditor::Button9);
	mem_delete(SXParticlesEditor::Button10);
	mem_delete(SXParticlesEditor::Button11);
	mem_delete(SXParticlesEditor::Button12);
	mem_delete(SXParticlesEditor::Button13);
	mem_delete(SXParticlesEditor::StaticBoundType);
	mem_delete(SXParticlesEditor::ComboBoxBoundType);
	mem_delete(SXParticlesEditor::StaticVector1);
	mem_delete(SXParticlesEditor::StaticVec1X);
	mem_delete(SXParticlesEditor::EditVec1X);
	mem_delete(SXParticlesEditor::StaticVec1Y);
	mem_delete(SXParticlesEditor::EditVec1Y);
	mem_delete(SXParticlesEditor::StaticVec1Z);
	mem_delete(SXParticlesEditor::EditVec1Z);
	mem_delete(SXParticlesEditor::StaticVec1W);
	mem_delete(SXParticlesEditor::EditVec1W);
	mem_delete(SXParticlesEditor::StaticVector2);
	mem_delete(SXParticlesEditor::StaticVec2X);
	mem_delete(SXParticlesEditor::EditVec2X);
	mem_delete(SXParticlesEditor::StaticVec2Y);
	mem_delete(SXParticlesEditor::EditVec2Y);
	mem_delete(SXParticlesEditor::StaticVec2Z);
	mem_delete(SXParticlesEditor::EditVec2Z);
	mem_delete(SXParticlesEditor::StaticVec2W);
	mem_delete(SXParticlesEditor::EditVec2W);
	mem_delete(SXParticlesEditor::JobWindow);
}
