#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXParticlesEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* Window1;
	ISXGUIToolBar* ToolBar1;
	ISXGUIListBox* ListBox1;
	ISXGUIListBox* ListBox2;
	ISXGUIStatic* Static1;
	ISXGUIButton* Button1;
	ISXGUIStatic* Static2;
	ISXGUIButton* Button2;
	ISXGUIButton* Button3;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIButton* Button10;
	ISXGUIButton* Button11;
	ISXGUIButton* Button12;
	ISXGUIButton* Button13;
	ISXGUIStatic* StaticName;
	ISXGUIEdit* EditName;
	ISXGUIStatic* StaticReCreateCount;
	ISXGUIEdit* EditReCreateCount;
	ISXGUIStatic* StaticSoftCoef;
	ISXGUIEdit* EditSoftCoef;
	ISXGUIStatic* StaticRefractionCoef;
	ISXGUIEdit* EditRefractionCoef;
	ISXGUIStatic* StaticTransparencyCoef;
	ISXGUIEdit* EditTransparencyCoef;
	ISXGUICheckBox* CheckBoxLighting;
	ISXGUIStatic* StaticFigureType;
	ISXGUIComboBox* ComboBoxFigureType;
	ISXGUIStatic* StaticFigureCountQuads;
	ISXGUIEdit* EditFigureCountQuads;
	ISXGUICheckBox* CheckBoxFigureRotRand;
	ISXGUICheckBox* CheckBoxFigureTapX;
	ISXGUICheckBox* CheckBoxFigureTapY;
	ISXGUICheckBox* CheckBoxFigureTapZ;
	ISXGUIStatic* StaticTimeLife;
	ISXGUIEdit* EditTimeLife;
	ISXGUIStatic* StaticTimeLifeDisp;
	ISXGUIEdit* EditTimeLifeDisp;
	ISXGUIStatic* StaticAlphaAgeDepend;
	ISXGUIComboBox* ComboBoxAlphaAgeDepend;
	ISXGUIStatic* StaticSize;
	ISXGUIStatic* StaticSizeX;
	ISXGUIEdit* EditSizeX;
	ISXGUIStatic* StaticSizeY;
	ISXGUIEdit* EditSizeY;
	ISXGUIStatic* StaticSizeDisp;
	ISXGUIEdit* EditSizeDisp;
	ISXGUIStatic* StaticSizeDependAge;
	ISXGUIComboBox* ComboBoxSizeDependAge;

	void InitAllElements();

	void DeleteAllElements();

};

void SXParticlesEditor::InitAllElements()
{
	SXParticlesEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,270,60,820,650,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXParticlesEditor::JobWindow);

	SXParticlesEditor::Window1 = SXGUICrBaseWnd("Window1","Window1",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXParticlesEditor::JobWindow->GetHWND(),0);
	SXParticlesEditor::ToolBar1 = SXGUICrToolBar("",0,1,804,24,804,24,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ListBox1 = SXGUICrListBox("",602,50,200,106,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox1->SetColorText(0,0,0);
	SXParticlesEditor::ListBox1->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox1->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox1->SetColorBrush(255,255,255);
	SXParticlesEditor::ListBox2 = SXGUICrListBox("",602,300,200,28,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox2->SetColorText(0,0,0);
	SXParticlesEditor::ListBox2->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox2->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox2->SetColorBrush(255,255,255);
	SXParticlesEditor::Static1 = SXGUICrStatic("Effects:",610,30,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static1->SetColorText(0,0,0);
	SXParticlesEditor::Static1->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static1->SetTransparentTextBk(true);
	SXParticlesEditor::Static1->SetColorBrush(220,220,220);
	SXParticlesEditor::Button1 = SXGUICrButton("Create",605,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2 = SXGUICrStatic("Particles:",610,275,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2->SetColorText(0,0,0);
	SXParticlesEditor::Static2->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static2->SetTransparentTextBk(true);
	SXParticlesEditor::Static2->SetColorBrush(220,220,220);
	SXParticlesEditor::Button2 = SXGUICrButton("Edit",670,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button3 = SXGUICrButton("Delete",735,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button4 = SXGUICrButton("Create",605,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button5 = SXGUICrButton("Edit",670,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button6 = SXGUICrButton("Delete",735,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button7 = SXGUICrButton("Base",25,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button8 = SXGUICrButton("TextureAnimTex",130,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button9 = SXGUICrButton("Spawn",235,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button10 = SXGUICrButton("Bound",340,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button10->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button11 = SXGUICrButton("Graphics",665,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button11->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button12 = SXGUICrButton("Charaters",560,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button12->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button13 = SXGUICrButton("VelocityAcceleration",445,434,110,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button13->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticName = SXGUICrStatic("Name:",5,460,40,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticName->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticName->SetColorText(0,0,0);
	SXParticlesEditor::StaticName->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticName->SetTransparentTextBk(true);
	SXParticlesEditor::StaticName->SetColorBrush(220,220,220);
	SXParticlesEditor::EditName = SXGUICrEdit("0",50,460,200,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditName->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditName->SetColorText(0,0,0);
	SXParticlesEditor::EditName->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditName->SetTransparentTextBk(true);
	SXParticlesEditor::EditName->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticReCreateCount = SXGUICrStatic("ReCreateCount:",5,480,75,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticReCreateCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticReCreateCount->SetColorText(0,0,0);
	SXParticlesEditor::StaticReCreateCount->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticReCreateCount->SetTransparentTextBk(true);
	SXParticlesEditor::StaticReCreateCount->SetColorBrush(220,220,220);
	SXParticlesEditor::EditReCreateCount = SXGUICrEdit("0",100,480,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditReCreateCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditReCreateCount->SetColorText(0,0,0);
	SXParticlesEditor::EditReCreateCount->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditReCreateCount->SetTransparentTextBk(true);
	SXParticlesEditor::EditReCreateCount->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSoftCoef = SXGUICrStatic("SoftCoef:",5,500,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSoftCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSoftCoef->SetColorText(0,0,0);
	SXParticlesEditor::StaticSoftCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSoftCoef->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSoftCoef->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSoftCoef = SXGUICrEdit("0",100,500,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSoftCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSoftCoef->SetColorText(0,0,0);
	SXParticlesEditor::EditSoftCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSoftCoef->SetTransparentTextBk(true);
	SXParticlesEditor::EditSoftCoef->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticRefractionCoef = SXGUICrStatic("RefractionCoef:",5,520,75,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticRefractionCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticRefractionCoef->SetColorText(0,0,0);
	SXParticlesEditor::StaticRefractionCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticRefractionCoef->SetTransparentTextBk(true);
	SXParticlesEditor::StaticRefractionCoef->SetColorBrush(220,220,220);
	SXParticlesEditor::EditRefractionCoef = SXGUICrEdit("0",100,520,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditRefractionCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditRefractionCoef->SetColorText(0,0,0);
	SXParticlesEditor::EditRefractionCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditRefractionCoef->SetTransparentTextBk(true);
	SXParticlesEditor::EditRefractionCoef->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticTransparencyCoef = SXGUICrStatic("TransparencyCoef:",5,540,90,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticTransparencyCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticTransparencyCoef->SetColorText(0,0,0);
	SXParticlesEditor::StaticTransparencyCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticTransparencyCoef->SetTransparentTextBk(true);
	SXParticlesEditor::StaticTransparencyCoef->SetColorBrush(220,220,220);
	SXParticlesEditor::EditTransparencyCoef = SXGUICrEdit("0",100,540,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditTransparencyCoef->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditTransparencyCoef->SetColorText(0,0,0);
	SXParticlesEditor::EditTransparencyCoef->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditTransparencyCoef->SetTransparentTextBk(true);
	SXParticlesEditor::EditTransparencyCoef->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxLighting = SXGUICrCheckBox("Lighting",5,560,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxLighting->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxLighting->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxLighting->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxLighting->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxLighting->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticFigureType = SXGUICrStatic("FigureType:",270,462,60,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticFigureType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticFigureType->SetColorText(0,0,0);
	SXParticlesEditor::StaticFigureType->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticFigureType->SetTransparentTextBk(true);
	SXParticlesEditor::StaticFigureType->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxFigureType = SXGUICrComboBox("",335,460,170,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxFigureType->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxFigureType->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxFigureType->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxFigureType->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxFigureType->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticFigureCountQuads = SXGUICrStatic("FigureCountQuads:",270,485,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticFigureCountQuads->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticFigureCountQuads->SetColorText(0,0,0);
	SXParticlesEditor::StaticFigureCountQuads->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticFigureCountQuads->SetTransparentTextBk(true);
	SXParticlesEditor::StaticFigureCountQuads->SetColorBrush(220,220,220);
	SXParticlesEditor::EditFigureCountQuads = SXGUICrEdit("0",375,485,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditFigureCountQuads->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditFigureCountQuads->SetColorText(0,0,0);
	SXParticlesEditor::EditFigureCountQuads->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditFigureCountQuads->SetTransparentTextBk(true);
	SXParticlesEditor::EditFigureCountQuads->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxFigureRotRand = SXGUICrCheckBox("FigureRotRand",270,505,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxFigureRotRand->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxFigureRotRand->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxFigureRotRand->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxFigureRotRand->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxFigureRotRand->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxFigureTapX = SXGUICrCheckBox("FigureTapX",270,525,75,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxFigureTapX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxFigureTapX->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxFigureTapX->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxFigureTapX->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxFigureTapX->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxFigureTapY = SXGUICrCheckBox("FigureTapY",350,525,75,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxFigureTapY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxFigureTapY->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxFigureTapY->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxFigureTapY->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxFigureTapY->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxFigureTapZ = SXGUICrCheckBox("FigureTapZ",430,525,75,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxFigureTapZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxFigureTapZ->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxFigureTapZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxFigureTapZ->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxFigureTapZ->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticTimeLife = SXGUICrStatic("TimeLife:",530,460,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticTimeLife->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticTimeLife->SetColorText(0,0,0);
	SXParticlesEditor::StaticTimeLife->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticTimeLife->SetTransparentTextBk(true);
	SXParticlesEditor::StaticTimeLife->SetColorBrush(220,220,220);
	SXParticlesEditor::EditTimeLife = SXGUICrEdit("0",585,460,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditTimeLife->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditTimeLife->SetColorText(0,0,0);
	SXParticlesEditor::EditTimeLife->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditTimeLife->SetTransparentTextBk(true);
	SXParticlesEditor::EditTimeLife->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticTimeLifeDisp = SXGUICrStatic("TimeLifeDisp:",660,460,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticTimeLifeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticTimeLifeDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticTimeLifeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticTimeLifeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticTimeLifeDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditTimeLifeDisp = SXGUICrEdit("0",730,460,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditTimeLifeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditTimeLifeDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditTimeLifeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditTimeLifeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditTimeLifeDisp->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticAlphaAgeDepend = SXGUICrStatic("AlphaAgeDepend:",530,482,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAlphaAgeDepend->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAlphaAgeDepend->SetColorText(0,0,0);
	SXParticlesEditor::StaticAlphaAgeDepend->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAlphaAgeDepend->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAlphaAgeDepend->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxAlphaAgeDepend = SXGUICrComboBox("",630,480,170,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxAlphaAgeDepend->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxAlphaAgeDepend->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxAlphaAgeDepend->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxAlphaAgeDepend->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxAlphaAgeDepend->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSize = SXGUICrStatic("Size:",530,505,25,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSize->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSize->SetColorText(0,0,0);
	SXParticlesEditor::StaticSize->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSize->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSize->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticSizeX = SXGUICrStatic("x:",555,505,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSizeX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSizeX->SetColorText(0,0,0);
	SXParticlesEditor::StaticSizeX->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSizeX->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSizeX->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSizeX = SXGUICrEdit("0",565,505,65,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSizeX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSizeX->SetColorText(0,0,0);
	SXParticlesEditor::EditSizeX->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSizeX->SetTransparentTextBk(true);
	SXParticlesEditor::EditSizeX->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSizeY = SXGUICrStatic("y:",635,505,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSizeY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSizeY->SetColorText(0,0,0);
	SXParticlesEditor::StaticSizeY->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSizeY->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSizeY->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSizeY = SXGUICrEdit("0",645,505,65,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSizeY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSizeY->SetColorText(0,0,0);
	SXParticlesEditor::EditSizeY->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSizeY->SetTransparentTextBk(true);
	SXParticlesEditor::EditSizeY->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSizeDisp = SXGUICrStatic("Disp:",710,505,25,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSizeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSizeDisp->SetColorText(0,0,0);
	SXParticlesEditor::StaticSizeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSizeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSizeDisp->SetColorBrush(220,220,220);
	SXParticlesEditor::EditSizeDisp = SXGUICrEdit("0",735,505,65,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditSizeDisp->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditSizeDisp->SetColorText(0,0,0);
	SXParticlesEditor::EditSizeDisp->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditSizeDisp->SetTransparentTextBk(true);
	SXParticlesEditor::EditSizeDisp->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticSizeDependAge = SXGUICrStatic("SizeDependAge:",530,527,100,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticSizeDependAge->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticSizeDependAge->SetColorText(0,0,0);
	SXParticlesEditor::StaticSizeDependAge->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticSizeDependAge->SetTransparentTextBk(true);
	SXParticlesEditor::StaticSizeDependAge->SetColorBrush(220,220,220);
	SXParticlesEditor::ComboBoxSizeDependAge = SXGUICrComboBox("",630,525,170,21,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ComboBoxSizeDependAge->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ComboBoxSizeDependAge->SetColorText(0,0,0);
	SXParticlesEditor::ComboBoxSizeDependAge->SetColorTextBk(255,255,255);
	SXParticlesEditor::ComboBoxSizeDependAge->SetTransparentTextBk(true);
	SXParticlesEditor::ComboBoxSizeDependAge->SetColorBrush(255,255,255);
}
void SXParticlesEditor::DeleteAllElements()
{
	mem_delete(SXParticlesEditor::Window1);
	mem_delete(SXParticlesEditor::ToolBar1);
	mem_delete(SXParticlesEditor::ListBox1);
	mem_delete(SXParticlesEditor::ListBox2);
	mem_delete(SXParticlesEditor::Static1);
	mem_delete(SXParticlesEditor::Button1);
	mem_delete(SXParticlesEditor::Static2);
	mem_delete(SXParticlesEditor::Button2);
	mem_delete(SXParticlesEditor::Button3);
	mem_delete(SXParticlesEditor::Button4);
	mem_delete(SXParticlesEditor::Button5);
	mem_delete(SXParticlesEditor::Button6);
	mem_delete(SXParticlesEditor::Button7);
	mem_delete(SXParticlesEditor::Button8);
	mem_delete(SXParticlesEditor::Button9);
	mem_delete(SXParticlesEditor::Button10);
	mem_delete(SXParticlesEditor::Button11);
	mem_delete(SXParticlesEditor::Button12);
	mem_delete(SXParticlesEditor::Button13);
	mem_delete(SXParticlesEditor::StaticName);
	mem_delete(SXParticlesEditor::EditName);
	mem_delete(SXParticlesEditor::StaticReCreateCount);
	mem_delete(SXParticlesEditor::EditReCreateCount);
	mem_delete(SXParticlesEditor::StaticSoftCoef);
	mem_delete(SXParticlesEditor::EditSoftCoef);
	mem_delete(SXParticlesEditor::StaticRefractionCoef);
	mem_delete(SXParticlesEditor::EditRefractionCoef);
	mem_delete(SXParticlesEditor::StaticTransparencyCoef);
	mem_delete(SXParticlesEditor::EditTransparencyCoef);
	mem_delete(SXParticlesEditor::CheckBoxLighting);
	mem_delete(SXParticlesEditor::StaticFigureType);
	mem_delete(SXParticlesEditor::ComboBoxFigureType);
	mem_delete(SXParticlesEditor::StaticFigureCountQuads);
	mem_delete(SXParticlesEditor::EditFigureCountQuads);
	mem_delete(SXParticlesEditor::CheckBoxFigureRotRand);
	mem_delete(SXParticlesEditor::CheckBoxFigureTapX);
	mem_delete(SXParticlesEditor::CheckBoxFigureTapY);
	mem_delete(SXParticlesEditor::CheckBoxFigureTapZ);
	mem_delete(SXParticlesEditor::StaticTimeLife);
	mem_delete(SXParticlesEditor::EditTimeLife);
	mem_delete(SXParticlesEditor::StaticTimeLifeDisp);
	mem_delete(SXParticlesEditor::EditTimeLifeDisp);
	mem_delete(SXParticlesEditor::StaticAlphaAgeDepend);
	mem_delete(SXParticlesEditor::ComboBoxAlphaAgeDepend);
	mem_delete(SXParticlesEditor::StaticSize);
	mem_delete(SXParticlesEditor::StaticSizeX);
	mem_delete(SXParticlesEditor::EditSizeX);
	mem_delete(SXParticlesEditor::StaticSizeY);
	mem_delete(SXParticlesEditor::EditSizeY);
	mem_delete(SXParticlesEditor::StaticSizeDisp);
	mem_delete(SXParticlesEditor::EditSizeDisp);
	mem_delete(SXParticlesEditor::StaticSizeDependAge);
	mem_delete(SXParticlesEditor::ComboBoxSizeDependAge);
	mem_delete(SXParticlesEditor::JobWindow);
}
