#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXParticlesEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* Window1;
	ISXGUIToolBar* ToolBar1;
	ISXGUIListBox* ListBox1;
	ISXGUIListBox* ListBox2;
	ISXGUIStatic* Static1;
	ISXGUIButton* Button1;
	ISXGUIStatic* Static2;
	ISXGUIButton* Button2;
	ISXGUIButton* Button3;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIButton* Button10;
	ISXGUIButton* Button11;
	ISXGUIButton* Button12;
	ISXGUIButton* Button13;
	ISXGUIStatic* StaticVelosity;
	ISXGUIStatic* StaticVelosityX;
	ISXGUIEdit* EditVelosityX;
	ISXGUIStatic* StaticVelosityY;
	ISXGUIEdit* EditVelosityY;
	ISXGUICheckBox* CheckBoxXDispNeg;
	ISXGUIStatic* StaticVelosityZ;
	ISXGUIEdit* EditVelosityZ;
	ISXGUIStatic* StaticDispersion;
	ISXGUIEdit* EditVelocityDispersion;
	ISXGUICheckBox* CheckBoxYDispNeg;
	ISXGUICheckBox* CheckBoxZDispNeg;
	ISXGUIStatic* StaticAcceleration;
	ISXGUIStatic* StaticAccelerationX;
	ISXGUIEdit* EditAccelerationX;
	ISXGUIStatic* StaticAccelerationY;
	ISXGUIEdit* EditAccelerationY;
	ISXGUIStatic* StaticAccelerationZ;
	ISXGUIEdit* EditAccelerationZ;
	ISXGUIStatic* StaticAccelerationDispersion;
	ISXGUIEdit* EditAccelerationDispersion;
	ISXGUICheckBox* CheckBoxXDispNeg;
	ISXGUICheckBox* CheckBoxYDispNeg;
	ISXGUICheckBox* CheckBoxZDispNeg;

	void InitAllElements();

	void DeleteAllElements();

};

void SXParticlesEditor::InitAllElements()
{
	SXParticlesEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,237,74,820,650,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXParticlesEditor::JobWindow);

	SXParticlesEditor::Window1 = SXGUICrBaseWnd("Window1","Window1",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXParticlesEditor::JobWindow->GetHWND(),0);
	SXParticlesEditor::ToolBar1 = SXGUICrToolBar("",0,1,804,24,804,24,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::ListBox1 = SXGUICrListBox("",602,50,200,145,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox1->SetColorText(0,0,0);
	SXParticlesEditor::ListBox1->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox1->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox1->SetColorBrush(255,255,255);
	SXParticlesEditor::ListBox2 = SXGUICrListBox("",602,300,200,54,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::ListBox2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::ListBox2->SetColorText(0,0,0);
	SXParticlesEditor::ListBox2->SetColorTextBk(255,255,255);
	SXParticlesEditor::ListBox2->SetTransparentTextBk(true);
	SXParticlesEditor::ListBox2->SetColorBrush(255,255,255);
	SXParticlesEditor::Static1 = SXGUICrStatic("Effects:",610,30,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static1->SetColorText(0,0,0);
	SXParticlesEditor::Static1->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static1->SetTransparentTextBk(true);
	SXParticlesEditor::Static1->SetColorBrush(220,220,220);
	SXParticlesEditor::Button1 = SXGUICrButton("Create",605,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2 = SXGUICrStatic("Particles:",610,275,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Static2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Static2->SetColorText(0,0,0);
	SXParticlesEditor::Static2->SetColorTextBk(255,255,255);
	SXParticlesEditor::Static2->SetTransparentTextBk(true);
	SXParticlesEditor::Static2->SetColorBrush(220,220,220);
	SXParticlesEditor::Button2 = SXGUICrButton("Edit",670,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button3 = SXGUICrButton("Delete",735,245,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button4 = SXGUICrButton("Create",605,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button5 = SXGUICrButton("Edit",670,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button6 = SXGUICrButton("Delete",735,410,60,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button7 = SXGUICrButton("Base",25,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button8 = SXGUICrButton("TextureAnimTex",130,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button9 = SXGUICrButton("Spawn",235,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button10 = SXGUICrButton("Bound",340,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button10->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button11 = SXGUICrButton("Graphics",665,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button11->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button12 = SXGUICrButton("Charaters",560,435,100,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button12->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::Button13 = SXGUICrButton("VelocityAcceleration",445,434,110,15,0,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::Button13->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVelosity = SXGUICrStatic("Velosity:",5,465,50,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVelosity->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVelosity->SetColorText(0,0,0);
	SXParticlesEditor::StaticVelosity->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVelosity->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVelosity->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticVelosityX = SXGUICrStatic("x:",80,465,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVelosityX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVelosityX->SetColorText(0,0,0);
	SXParticlesEditor::StaticVelosityX->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVelosityX->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVelosityX->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVelosityX = SXGUICrEdit("0",90,465,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVelosityX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVelosityX->SetColorText(0,0,0);
	SXParticlesEditor::EditVelosityX->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVelosityX->SetTransparentTextBk(true);
	SXParticlesEditor::EditVelosityX->SetColorBrush(250,250,250);
	SXParticlesEditor::StaticVelosityY = SXGUICrStatic("y:",170,465,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVelosityY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVelosityY->SetColorText(0,0,0);
	SXParticlesEditor::StaticVelosityY->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVelosityY->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVelosityY->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVelosityY = SXGUICrEdit("0",180,465,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVelosityY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVelosityY->SetColorText(0,0,0);
	SXParticlesEditor::EditVelosityY->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVelosityY->SetTransparentTextBk(true);
	SXParticlesEditor::EditVelosityY->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxXDispNeg = SXGUICrCheckBox("XDispNeg",80,485,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxXDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxXDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticVelosityZ = SXGUICrStatic("z:",260,465,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticVelosityZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticVelosityZ->SetColorText(0,0,0);
	SXParticlesEditor::StaticVelosityZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticVelosityZ->SetTransparentTextBk(true);
	SXParticlesEditor::StaticVelosityZ->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVelosityZ = SXGUICrEdit("0",270,465,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVelosityZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVelosityZ->SetColorText(0,0,0);
	SXParticlesEditor::EditVelosityZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVelosityZ->SetTransparentTextBk(true);
	SXParticlesEditor::EditVelosityZ->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticDispersion = SXGUICrStatic("Dispersion:",355,465,60,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticDispersion->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticDispersion->SetColorText(0,0,0);
	SXParticlesEditor::StaticDispersion->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticDispersion->SetTransparentTextBk(true);
	SXParticlesEditor::StaticDispersion->SetColorBrush(220,220,220);
	SXParticlesEditor::EditVelocityDispersion = SXGUICrEdit("0",420,465,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditVelocityDispersion->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditVelocityDispersion->SetColorText(0,0,0);
	SXParticlesEditor::EditVelocityDispersion->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditVelocityDispersion->SetTransparentTextBk(true);
	SXParticlesEditor::EditVelocityDispersion->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxYDispNeg = SXGUICrCheckBox("YDispNeg",170,485,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxYDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxYDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxZDispNeg = SXGUICrCheckBox("ZDispNeg",260,485,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxZDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxZDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticAcceleration = SXGUICrStatic("Acceleration:",5,515,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAcceleration->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAcceleration->SetColorText(0,0,0);
	SXParticlesEditor::StaticAcceleration->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAcceleration->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAcceleration->SetColorBrush(220,220,220);
	SXParticlesEditor::StaticAccelerationX = SXGUICrStatic("x:",80,515,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAccelerationX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAccelerationX->SetColorText(0,0,0);
	SXParticlesEditor::StaticAccelerationX->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAccelerationX->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAccelerationX->SetColorBrush(220,220,220);
	SXParticlesEditor::EditAccelerationX = SXGUICrEdit("0",90,515,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditAccelerationX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditAccelerationX->SetColorText(0,0,0);
	SXParticlesEditor::EditAccelerationX->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditAccelerationX->SetTransparentTextBk(true);
	SXParticlesEditor::EditAccelerationX->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticAccelerationY = SXGUICrStatic("y:",170,515,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAccelerationY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAccelerationY->SetColorText(0,0,0);
	SXParticlesEditor::StaticAccelerationY->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAccelerationY->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAccelerationY->SetColorBrush(220,220,220);
	SXParticlesEditor::EditAccelerationY = SXGUICrEdit("0",180,515,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditAccelerationY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditAccelerationY->SetColorText(0,0,0);
	SXParticlesEditor::EditAccelerationY->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditAccelerationY->SetTransparentTextBk(true);
	SXParticlesEditor::EditAccelerationY->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticAccelerationZ = SXGUICrStatic("z:",260,515,10,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAccelerationZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAccelerationZ->SetColorText(0,0,0);
	SXParticlesEditor::StaticAccelerationZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAccelerationZ->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAccelerationZ->SetColorBrush(220,220,220);
	SXParticlesEditor::EditAccelerationZ = SXGUICrEdit("0",270,515,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditAccelerationZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditAccelerationZ->SetColorText(0,0,0);
	SXParticlesEditor::EditAccelerationZ->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditAccelerationZ->SetTransparentTextBk(true);
	SXParticlesEditor::EditAccelerationZ->SetColorBrush(255,255,255);
	SXParticlesEditor::StaticAccelerationDispersion = SXGUICrStatic("Dispersion:",355,515,60,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::StaticAccelerationDispersion->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::StaticAccelerationDispersion->SetColorText(0,0,0);
	SXParticlesEditor::StaticAccelerationDispersion->SetColorTextBk(255,255,255);
	SXParticlesEditor::StaticAccelerationDispersion->SetTransparentTextBk(true);
	SXParticlesEditor::StaticAccelerationDispersion->SetColorBrush(220,220,220);
	SXParticlesEditor::EditAccelerationDispersion = SXGUICrEdit("0",420,515,70,15,SXParticlesEditor::JobWindow->GetHWND(),0,0);
	SXParticlesEditor::EditAccelerationDispersion->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::EditAccelerationDispersion->SetColorText(0,0,0);
	SXParticlesEditor::EditAccelerationDispersion->SetColorTextBk(255,255,255);
	SXParticlesEditor::EditAccelerationDispersion->SetTransparentTextBk(true);
	SXParticlesEditor::EditAccelerationDispersion->SetColorBrush(255,255,255);
	SXParticlesEditor::CheckBoxXDispNeg = SXGUICrCheckBox("XDispNeg",80,535,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxXDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxXDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxXDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxYDispNeg = SXGUICrCheckBox("YDispNeg",170,535,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxYDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxYDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxYDispNeg->SetColorBrush(220,220,220);
	SXParticlesEditor::CheckBoxZDispNeg = SXGUICrCheckBox("ZDispNeg",260,535,80,15,SXParticlesEditor::JobWindow->GetHWND(),0,0,true);
	SXParticlesEditor::CheckBoxZDispNeg->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorText(0,0,0);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorTextBk(255,255,255);
	SXParticlesEditor::CheckBoxZDispNeg->SetTransparentTextBk(true);
	SXParticlesEditor::CheckBoxZDispNeg->SetColorBrush(220,220,220);
}
void SXParticlesEditor::DeleteAllElements()
{
	mem_delete(SXParticlesEditor::Window1);
	mem_delete(SXParticlesEditor::ToolBar1);
	mem_delete(SXParticlesEditor::ListBox1);
	mem_delete(SXParticlesEditor::ListBox2);
	mem_delete(SXParticlesEditor::Static1);
	mem_delete(SXParticlesEditor::Button1);
	mem_delete(SXParticlesEditor::Static2);
	mem_delete(SXParticlesEditor::Button2);
	mem_delete(SXParticlesEditor::Button3);
	mem_delete(SXParticlesEditor::Button4);
	mem_delete(SXParticlesEditor::Button5);
	mem_delete(SXParticlesEditor::Button6);
	mem_delete(SXParticlesEditor::Button7);
	mem_delete(SXParticlesEditor::Button8);
	mem_delete(SXParticlesEditor::Button9);
	mem_delete(SXParticlesEditor::Button10);
	mem_delete(SXParticlesEditor::Button11);
	mem_delete(SXParticlesEditor::Button12);
	mem_delete(SXParticlesEditor::Button13);
	mem_delete(SXParticlesEditor::StaticVelosity);
	mem_delete(SXParticlesEditor::StaticVelosityX);
	mem_delete(SXParticlesEditor::EditVelosityX);
	mem_delete(SXParticlesEditor::StaticVelosityY);
	mem_delete(SXParticlesEditor::EditVelosityY);
	mem_delete(SXParticlesEditor::CheckBoxXDispNeg);
	mem_delete(SXParticlesEditor::StaticVelosityZ);
	mem_delete(SXParticlesEditor::EditVelosityZ);
	mem_delete(SXParticlesEditor::StaticDispersion);
	mem_delete(SXParticlesEditor::EditVelocityDispersion);
	mem_delete(SXParticlesEditor::CheckBoxYDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxZDispNeg);
	mem_delete(SXParticlesEditor::StaticAcceleration);
	mem_delete(SXParticlesEditor::StaticAccelerationX);
	mem_delete(SXParticlesEditor::EditAccelerationX);
	mem_delete(SXParticlesEditor::StaticAccelerationY);
	mem_delete(SXParticlesEditor::EditAccelerationY);
	mem_delete(SXParticlesEditor::StaticAccelerationZ);
	mem_delete(SXParticlesEditor::EditAccelerationZ);
	mem_delete(SXParticlesEditor::StaticAccelerationDispersion);
	mem_delete(SXParticlesEditor::EditAccelerationDispersion);
	mem_delete(SXParticlesEditor::CheckBoxXDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxYDispNeg);
	mem_delete(SXParticlesEditor::CheckBoxZDispNeg);
	mem_delete(SXParticlesEditor::JobWindow);
}
