#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXLevelEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* RenderWindow;
	ISXGUIToolBar* ToolBar1;
	ISXGUIGroupBox* GroupBoxList;
	ISXGUIGroupBox* GroupBoxData;
	ISXGUIListBox* ListBoxList;
	ISXGUIStatic* StaticListTextCount;
	ISXGUIStatic* StaticListValCount;
	ISXGUIButton* ButtonGeometryOpen;
	ISXGUIButton* ButtonGreenOpen;
	ISXGUIButton* ButtonLightOpen;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIStatic* StaticName;
	ISXGUIStatic* StaticModel;
	ISXGUIStatic* StaticLod1;
	ISXGUIStatic* StaticLod2;
	ISXGUIEdit* EditName;
	ISXGUIEdit* EditModel;
	ISXGUIEdit* EditLod1;
	ISXGUIEdit* EditLod2;
	ISXGUIButton* ButtonLod1;
	ISXGUIButton* ButtonModel;
	ISXGUIButton* ButtonLod2;
	ISXGUIButton* ButtonMask;
	ISXGUIStatic* StaticMask;
	ISXGUIEdit* EditMask;
	ISXGUIStatusBar* StatusBar1;
	ISXGUIStatic* StaticPos;
	ISXGUIEdit* EditPosX;
	ISXGUIEdit* EditPosY;
	ISXGUIEdit* EditPosZ;
	ISXGUIRadioButton* RadioButtonPosX;
	ISXGUIRadioButton* RadioButtonPosY;
	ISXGUIRadioButton* RadioButtonPosZ;
	ISXGUIStatic* StaticRot;
	ISXGUIEdit* EditRotX;
	ISXGUIEdit* EditRotY;
	ISXGUIEdit* EditRotZ;
	ISXGUIRadioButton* RadioButtonRotX;
	ISXGUIRadioButton* RadioButtonRotY;
	ISXGUIRadioButton* RadioButtonRotZ;
	ISXGUIStatic* StaticScale;
	ISXGUIEdit* EditScaleX;
	ISXGUIEdit* EditScaleY;
	ISXGUIEdit* EditScaleZ;
	ISXGUIRadioButton* RadioButtonScaleX;
	ISXGUIRadioButton* RadioButtonScaleY;
	ISXGUIRadioButton* RadioButtonScaleZ;
	ISXGUICheckBox* CheckBoxCG;
	ISXGUIButton* ButtonFinish;

	void InitAllElements();

	void DeleteAllElements();

};

void SXLevelEditor::InitAllElements()
{
	SXLevelEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,320,63,820,620,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXLevelEditor::JobWindow);

	SXLevelEditor::RenderWindow = SXGUICrBaseWnd("RenderWindow","RenderWindow",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXLevelEditor::JobWindow->GetHWND(),0);
	SXLevelEditor::ToolBar1 = SXGUICrToolBar("",0,1,810,24,810,24,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxList = SXGUICrGroupBox("GroupBoxList",601,26,200,400,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxList->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::GroupBoxList->SetColorText(0,0,0);
	SXLevelEditor::GroupBoxList->SetColorTextBk(255,255,255);
	SXLevelEditor::GroupBoxList->SetTransparentTextBk(true);
	SXLevelEditor::GroupBoxList->SetColorBrush(220,220,220);
	SXLevelEditor::GroupBoxData = SXGUICrGroupBox("GroupBoxData",0,425,800,120,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxData->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::GroupBoxData->SetColorText(0,0,0);
	SXLevelEditor::GroupBoxData->SetColorTextBk(255,255,255);
	SXLevelEditor::GroupBoxData->SetTransparentTextBk(true);
	SXLevelEditor::GroupBoxData->SetColorBrush(220,220,220);
	SXLevelEditor::ListBoxList = SXGUICrListBox("",604,56,193,290,SXLevelEditor::JobWindow->GetHWND(),0,0,true);
	SXLevelEditor::ListBoxList->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ListBoxList->SetColorText(0,0,0);
	SXLevelEditor::ListBoxList->SetColorTextBk(255,255,255);
	SXLevelEditor::ListBoxList->SetTransparentTextBk(true);
	SXLevelEditor::ListBoxList->SetColorBrush(255,255,255);
	SXLevelEditor::StaticListTextCount = SXGUICrStatic("Count:",665,41,30,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticListTextCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticListTextCount->SetColorText(0,0,0);
	SXLevelEditor::StaticListTextCount->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticListTextCount->SetTransparentTextBk(true);
	SXLevelEditor::StaticListTextCount->SetColorBrush(220,220,220);
	SXLevelEditor::StaticListValCount = SXGUICrStatic("0",700,41,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticListValCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticListValCount->SetColorText(0,0,0);
	SXLevelEditor::StaticListValCount->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticListValCount->SetTransparentTextBk(true);
	SXLevelEditor::StaticListValCount->SetColorBrush(220,220,220);
	SXLevelEditor::ButtonGeometryOpen = SXGUICrButton("Geometry",605,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGeometryOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonGreenOpen = SXGUICrButton("Green",670,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGreenOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonLightOpen = SXGUICrButton("Light",735,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonLightOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button4 = SXGUICrButton("other",605,375,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button5 = SXGUICrButton("other",605,400,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticName = SXGUICrStatic("Name",5,440,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticName->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticName->SetColorText(0,0,0);
	SXLevelEditor::StaticName->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticName->SetTransparentTextBk(true);
	SXLevelEditor::StaticName->SetColorBrush(220,220,220);
	SXLevelEditor::StaticModel = SXGUICrStatic("Model",5,460,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticModel->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticModel->SetColorText(0,0,0);
	SXLevelEditor::StaticModel->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticModel->SetTransparentTextBk(true);
	SXLevelEditor::StaticModel->SetColorBrush(220,220,220);
	SXLevelEditor::StaticLod1 = SXGUICrStatic("Lod1",5,480,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticLod1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticLod1->SetColorText(0,0,0);
	SXLevelEditor::StaticLod1->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticLod1->SetTransparentTextBk(true);
	SXLevelEditor::StaticLod1->SetColorBrush(220,220,220);
	SXLevelEditor::StaticLod2 = SXGUICrStatic("Lod2",5,500,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticLod2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticLod2->SetColorText(0,0,0);
	SXLevelEditor::StaticLod2->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticLod2->SetTransparentTextBk(true);
	SXLevelEditor::StaticLod2->SetColorBrush(220,220,220);
	SXLevelEditor::EditName = SXGUICrEdit("0",80,440,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditName->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditName->SetColorText(0,0,0);
	SXLevelEditor::EditName->SetColorTextBk(255,255,255);
	SXLevelEditor::EditName->SetTransparentTextBk(true);
	SXLevelEditor::EditName->SetColorBrush(255,255,255);
	SXLevelEditor::EditModel = SXGUICrEdit("0",80,460,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditModel->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditModel->SetColorText(0,0,0);
	SXLevelEditor::EditModel->SetColorTextBk(255,255,255);
	SXLevelEditor::EditModel->SetTransparentTextBk(true);
	SXLevelEditor::EditModel->SetColorBrush(255,255,255);
	SXLevelEditor::EditLod1 = SXGUICrEdit("0",80,480,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditLod1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditLod1->SetColorText(0,0,0);
	SXLevelEditor::EditLod1->SetColorTextBk(255,255,255);
	SXLevelEditor::EditLod1->SetTransparentTextBk(true);
	SXLevelEditor::EditLod1->SetColorBrush(255,255,255);
	SXLevelEditor::EditLod2 = SXGUICrEdit("0",80,500,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditLod2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditLod2->SetColorText(0,0,0);
	SXLevelEditor::EditLod2->SetColorTextBk(255,255,255);
	SXLevelEditor::EditLod2->SetTransparentTextBk(true);
	SXLevelEditor::EditLod2->SetColorBrush(255,255,255);
	SXLevelEditor::ButtonLod1 = SXGUICrButton("...",285,480,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonLod1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonModel = SXGUICrButton("...",285,460,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonModel->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonLod2 = SXGUICrButton("...",285,500,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonLod2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonMask = SXGUICrButton("...",285,520,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonMask->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticMask = SXGUICrStatic("Mask texture",5,520,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticMask->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticMask->SetColorText(0,0,0);
	SXLevelEditor::StaticMask->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticMask->SetTransparentTextBk(true);
	SXLevelEditor::StaticMask->SetColorBrush(220,220,220);
	SXLevelEditor::EditMask = SXGUICrEdit("0",80,520,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditMask->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditMask->SetColorText(0,0,0);
	SXLevelEditor::EditMask->SetColorTextBk(255,255,255);
	SXLevelEditor::EditMask->SetTransparentTextBk(true);
	SXLevelEditor::EditMask->SetColorBrush(255,255,255);
	SXLevelEditor::StatusBar1 = SXGUICrStatusBar("StatusBar1",SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StatusBar1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticPos = SXGUICrStatic("Position:",320,455,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticPos->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticPos->SetColorText(0,0,0);
	SXLevelEditor::StaticPos->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticPos->SetTransparentTextBk(true);
	SXLevelEditor::StaticPos->SetColorBrush(220,220,220);
	SXLevelEditor::EditPosX = SXGUICrEdit("0",370,435,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditPosX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditPosX->SetColorText(0,0,0);
	SXLevelEditor::EditPosX->SetColorTextBk(255,255,255);
	SXLevelEditor::EditPosX->SetTransparentTextBk(true);
	SXLevelEditor::EditPosX->SetColorBrush(255,255,255);
	SXLevelEditor::EditPosY = SXGUICrEdit("0",370,455,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditPosY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditPosY->SetColorText(0,0,0);
	SXLevelEditor::EditPosY->SetColorTextBk(255,255,255);
	SXLevelEditor::EditPosY->SetTransparentTextBk(true);
	SXLevelEditor::EditPosY->SetColorBrush(255,255,255);
	SXLevelEditor::EditPosZ = SXGUICrEdit("0",370,475,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditPosZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditPosZ->SetColorText(0,0,0);
	SXLevelEditor::EditPosZ->SetColorTextBk(255,255,255);
	SXLevelEditor::EditPosZ->SetTransparentTextBk(true);
	SXLevelEditor::EditPosZ->SetColorBrush(255,255,255);
	SXLevelEditor::RadioButtonPosX = SXGUICrRadioButton("x",440,435,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonPosX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonPosX->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonPosX->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonPosX->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonPosX->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonPosY = SXGUICrRadioButton("y",440,455,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonPosY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonPosY->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonPosY->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonPosY->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonPosY->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonPosZ = SXGUICrRadioButton("z",440,475,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonPosZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonPosZ->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonPosZ->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonPosZ->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonPosZ->SetColorBrush(220,220,220);
	SXLevelEditor::StaticRot = SXGUICrStatic("Rotation:",470,455,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticRot->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticRot->SetColorText(0,0,0);
	SXLevelEditor::StaticRot->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticRot->SetTransparentTextBk(true);
	SXLevelEditor::StaticRot->SetColorBrush(220,220,220);
	SXLevelEditor::EditRotX = SXGUICrEdit("0",525,435,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditRotX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditRotX->SetColorText(0,0,0);
	SXLevelEditor::EditRotX->SetColorTextBk(255,255,255);
	SXLevelEditor::EditRotX->SetTransparentTextBk(true);
	SXLevelEditor::EditRotX->SetColorBrush(255,255,255);
	SXLevelEditor::EditRotY = SXGUICrEdit("0",525,455,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditRotY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditRotY->SetColorText(0,0,0);
	SXLevelEditor::EditRotY->SetColorTextBk(255,255,255);
	SXLevelEditor::EditRotY->SetTransparentTextBk(true);
	SXLevelEditor::EditRotY->SetColorBrush(255,255,255);
	SXLevelEditor::EditRotZ = SXGUICrEdit("0",525,475,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditRotZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditRotZ->SetColorText(0,0,0);
	SXLevelEditor::EditRotZ->SetColorTextBk(255,255,255);
	SXLevelEditor::EditRotZ->SetTransparentTextBk(true);
	SXLevelEditor::EditRotZ->SetColorBrush(255,255,255);
	SXLevelEditor::RadioButtonRotX = SXGUICrRadioButton("x",595,435,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonRotX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonRotX->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonRotX->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonRotX->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonRotX->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonRotY = SXGUICrRadioButton("y",595,455,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonRotY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonRotY->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonRotY->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonRotY->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonRotY->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonRotZ = SXGUICrRadioButton("z",595,475,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonRotZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonRotZ->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonRotZ->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonRotZ->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonRotZ->SetColorBrush(220,220,220);
	SXLevelEditor::StaticScale = SXGUICrStatic("Scale:",625,455,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticScale->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticScale->SetColorText(0,0,0);
	SXLevelEditor::StaticScale->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticScale->SetTransparentTextBk(true);
	SXLevelEditor::StaticScale->SetColorBrush(220,220,220);
	SXLevelEditor::EditScaleX = SXGUICrEdit("0",675,435,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditScaleX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditScaleX->SetColorText(0,0,0);
	SXLevelEditor::EditScaleX->SetColorTextBk(255,255,255);
	SXLevelEditor::EditScaleX->SetTransparentTextBk(true);
	SXLevelEditor::EditScaleX->SetColorBrush(255,255,255);
	SXLevelEditor::EditScaleY = SXGUICrEdit("0",675,455,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditScaleY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditScaleY->SetColorText(0,0,0);
	SXLevelEditor::EditScaleY->SetColorTextBk(255,255,255);
	SXLevelEditor::EditScaleY->SetTransparentTextBk(true);
	SXLevelEditor::EditScaleY->SetColorBrush(255,255,255);
	SXLevelEditor::EditScaleZ = SXGUICrEdit("0",675,475,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::EditScaleZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::EditScaleZ->SetColorText(0,0,0);
	SXLevelEditor::EditScaleZ->SetColorTextBk(255,255,255);
	SXLevelEditor::EditScaleZ->SetTransparentTextBk(true);
	SXLevelEditor::EditScaleZ->SetColorBrush(255,255,255);
	SXLevelEditor::RadioButtonScaleX = SXGUICrRadioButton("x",745,435,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonScaleX->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonScaleX->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonScaleX->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonScaleX->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonScaleX->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonScaleY = SXGUICrRadioButton("y",745,455,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonScaleY->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonScaleY->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonScaleY->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonScaleY->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonScaleY->SetColorBrush(220,220,220);
	SXLevelEditor::RadioButtonScaleZ = SXGUICrRadioButton("z",745,475,25,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::RadioButtonScaleZ->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::RadioButtonScaleZ->SetColorText(0,0,0);
	SXLevelEditor::RadioButtonScaleZ->SetColorTextBk(255,255,255);
	SXLevelEditor::RadioButtonScaleZ->SetTransparentTextBk(true);
	SXLevelEditor::RadioButtonScaleZ->SetColorBrush(220,220,220);
	SXLevelEditor::CheckBoxCG = SXGUICrCheckBox("Closed geometry",350,500,100,15,SXLevelEditor::JobWindow->GetHWND(),0,0,true);
	SXLevelEditor::CheckBoxCG->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::CheckBoxCG->SetColorText(0,0,0);
	SXLevelEditor::CheckBoxCG->SetColorTextBk(255,255,255);
	SXLevelEditor::CheckBoxCG->SetTransparentTextBk(true);
	SXLevelEditor::CheckBoxCG->SetColorBrush(220,220,220);
	SXLevelEditor::ButtonFinish = SXGUICrButton("Finish",350,520,100,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonFinish->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
}
void SXLevelEditor::DeleteAllElements()
{
	mem_delete(SXLevelEditor::RenderWindow);
	mem_delete(SXLevelEditor::ToolBar1);
	mem_delete(SXLevelEditor::GroupBoxList);
	mem_delete(SXLevelEditor::GroupBoxData);
	mem_delete(SXLevelEditor::ListBoxList);
	mem_delete(SXLevelEditor::StaticListTextCount);
	mem_delete(SXLevelEditor::StaticListValCount);
	mem_delete(SXLevelEditor::ButtonGeometryOpen);
	mem_delete(SXLevelEditor::ButtonGreenOpen);
	mem_delete(SXLevelEditor::ButtonLightOpen);
	mem_delete(SXLevelEditor::Button4);
	mem_delete(SXLevelEditor::Button5);
	mem_delete(SXLevelEditor::StaticName);
	mem_delete(SXLevelEditor::StaticModel);
	mem_delete(SXLevelEditor::StaticLod1);
	mem_delete(SXLevelEditor::StaticLod2);
	mem_delete(SXLevelEditor::EditName);
	mem_delete(SXLevelEditor::EditModel);
	mem_delete(SXLevelEditor::EditLod1);
	mem_delete(SXLevelEditor::EditLod2);
	mem_delete(SXLevelEditor::ButtonLod1);
	mem_delete(SXLevelEditor::ButtonModel);
	mem_delete(SXLevelEditor::ButtonLod2);
	mem_delete(SXLevelEditor::ButtonMask);
	mem_delete(SXLevelEditor::StaticMask);
	mem_delete(SXLevelEditor::EditMask);
	mem_delete(SXLevelEditor::StatusBar1);
	mem_delete(SXLevelEditor::StaticPos);
	mem_delete(SXLevelEditor::EditPosX);
	mem_delete(SXLevelEditor::EditPosY);
	mem_delete(SXLevelEditor::EditPosZ);
	mem_delete(SXLevelEditor::RadioButtonPosX);
	mem_delete(SXLevelEditor::RadioButtonPosY);
	mem_delete(SXLevelEditor::RadioButtonPosZ);
	mem_delete(SXLevelEditor::StaticRot);
	mem_delete(SXLevelEditor::EditRotX);
	mem_delete(SXLevelEditor::EditRotY);
	mem_delete(SXLevelEditor::EditRotZ);
	mem_delete(SXLevelEditor::RadioButtonRotX);
	mem_delete(SXLevelEditor::RadioButtonRotY);
	mem_delete(SXLevelEditor::RadioButtonRotZ);
	mem_delete(SXLevelEditor::StaticScale);
	mem_delete(SXLevelEditor::EditScaleX);
	mem_delete(SXLevelEditor::EditScaleY);
	mem_delete(SXLevelEditor::EditScaleZ);
	mem_delete(SXLevelEditor::RadioButtonScaleX);
	mem_delete(SXLevelEditor::RadioButtonScaleY);
	mem_delete(SXLevelEditor::RadioButtonScaleZ);
	mem_delete(SXLevelEditor::CheckBoxCG);
	mem_delete(SXLevelEditor::ButtonFinish);
	mem_delete(SXLevelEditor::JobWindow);
}
