#define mem_delete(p) if(p) {delete (p);(p) = NULL;}

namespace SXLevelEditor
{
	ISXGUIBaseWnd* JobWindow;
	ISXGUIBaseWnd* RenderWindow;
	ISXGUIToolBar* ToolBar1;
	ISXGUIGroupBox* GroupBoxList;
	ISXGUIGroupBox* GroupBoxData;
	ISXGUIListBox* ListBoxList;
	ISXGUIStatic* StaticListTextCount;
	ISXGUIStatic* StaticListValCount;
	ISXGUIButton* ButtonGeometryOpen;
	ISXGUIButton* ButtonGreenOpen;
	ISXGUIButton* ButtonLightOpen;
	ISXGUIButton* Button4;
	ISXGUIButton* Button5;
	ISXGUIStatic* Static3;
	ISXGUIStatic* Static4;
	ISXGUIStatic* Static5;
	ISXGUIStatic* Static6;
	ISXGUIEdit* Edit1;
	ISXGUIEdit* Edit2;
	ISXGUIEdit* Edit3;
	ISXGUIEdit* Edit4;
	ISXGUIButton* Button6;
	ISXGUIButton* Button7;
	ISXGUIButton* Button8;
	ISXGUIButton* Button9;
	ISXGUIStatic* Static7;
	ISXGUIEdit* Edit5;
	ISXGUIStatusBar* StatusBar1;
	ISXGUITrackBar* TrackBarDinsity;
	ISXGUIButton* ButtonGenerate;
	ISXGUIStatic* StaticDensityText;
	ISXGUIStatic* StaticDensityVal;

	void InitAllElements();

	void DeleteAllElements();

};

void SXLevelEditor::InitAllElements()
{
	SXLevelEditor::JobWindow = SXGUICrBaseWnd("JobWindow","JobWindow",0,0,320,63,820,620,0,0,CreateSolidBrush(RGB(220,220,220)),0,CS_HREDRAW | CS_VREDRAW,WS_THICKFRAME | WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION,0,WndProcAllDefault);
	SXGUIBaseHandlers::InitHandlerMsg(SXLevelEditor::JobWindow);

	SXLevelEditor::RenderWindow = SXGUICrBaseWnd("RenderWindow","RenderWindow",0,0,0,25,600,400,0,0,CreateSolidBrush(RGB(200,200,200)),0,CS_HREDRAW | CS_VREDRAW,WS_CHILD | WS_VISIBLE | WS_BORDER,SXLevelEditor::JobWindow->GetHWND(),0);
	SXLevelEditor::ToolBar1 = SXGUICrToolBar("",0,1,810,24,810,24,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxList = SXGUICrGroupBox("GroupBoxList",601,26,200,400,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxList->SetColorText(0,0,0);
	SXLevelEditor::GroupBoxList->SetColorTextBk(255,255,255);
	SXLevelEditor::GroupBoxList->SetTransparentTextBk(true);
	SXLevelEditor::GroupBoxList->SetColorBrush(220,220,220);
	SXLevelEditor::GroupBoxData = SXGUICrGroupBox("GroupBoxData",0,425,800,120,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::GroupBoxData->SetColorText(0,0,0);
	SXLevelEditor::GroupBoxData->SetColorTextBk(255,255,255);
	SXLevelEditor::GroupBoxData->SetTransparentTextBk(true);
	SXLevelEditor::GroupBoxData->SetColorBrush(220,220,220);
	SXLevelEditor::ListBoxList = SXGUICrListBox("",604,56,193,290,SXLevelEditor::JobWindow->GetHWND(),0,0,true);
	SXLevelEditor::ListBoxList->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ListBoxList->SetColorText(0,0,0);
	SXLevelEditor::ListBoxList->SetColorTextBk(255,255,255);
	SXLevelEditor::ListBoxList->SetTransparentTextBk(true);
	SXLevelEditor::ListBoxList->SetColorBrush(255,255,255);
	SXLevelEditor::StaticListTextCount = SXGUICrStatic("Count:",665,41,30,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticListTextCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticListTextCount->SetColorText(0,0,0);
	SXLevelEditor::StaticListTextCount->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticListTextCount->SetTransparentTextBk(true);
	SXLevelEditor::StaticListTextCount->SetColorBrush(220,220,220);
	SXLevelEditor::StaticListValCount = SXGUICrStatic("0",700,41,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticListValCount->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticListValCount->SetColorText(0,0,0);
	SXLevelEditor::StaticListValCount->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticListValCount->SetTransparentTextBk(true);
	SXLevelEditor::StaticListValCount->SetColorBrush(220,220,220);
	SXLevelEditor::ButtonGeometryOpen = SXGUICrButton("Geometry",605,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGeometryOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonGreenOpen = SXGUICrButton("Green",670,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGreenOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::ButtonLightOpen = SXGUICrButton("Light",735,350,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonLightOpen->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button4 = SXGUICrButton("other",605,375,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button5 = SXGUICrButton("other",605,400,60,20,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static3 = SXGUICrStatic("Name",5,440,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Static3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static3->SetColorText(0,0,0);
	SXLevelEditor::Static3->SetColorTextBk(255,255,255);
	SXLevelEditor::Static3->SetTransparentTextBk(true);
	SXLevelEditor::Static3->SetColorBrush(255,255,255);
	SXLevelEditor::Static4 = SXGUICrStatic("Model",5,460,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Static4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static4->SetColorText(0,0,0);
	SXLevelEditor::Static4->SetColorTextBk(255,255,255);
	SXLevelEditor::Static4->SetTransparentTextBk(true);
	SXLevelEditor::Static4->SetColorBrush(255,255,255);
	SXLevelEditor::Static5 = SXGUICrStatic("Lod1",5,480,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Static5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static5->SetColorText(0,0,0);
	SXLevelEditor::Static5->SetColorTextBk(255,255,255);
	SXLevelEditor::Static5->SetTransparentTextBk(true);
	SXLevelEditor::Static5->SetColorBrush(255,255,255);
	SXLevelEditor::Static6 = SXGUICrStatic("Lod2",5,500,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Static6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static6->SetColorText(0,0,0);
	SXLevelEditor::Static6->SetColorTextBk(255,255,255);
	SXLevelEditor::Static6->SetTransparentTextBk(true);
	SXLevelEditor::Static6->SetColorBrush(255,255,255);
	SXLevelEditor::Edit1 = SXGUICrEdit("0",80,440,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Edit1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Edit1->SetColorText(0,0,0);
	SXLevelEditor::Edit1->SetColorTextBk(255,255,255);
	SXLevelEditor::Edit1->SetTransparentTextBk(true);
	SXLevelEditor::Edit1->SetColorBrush(255,255,255);
	SXLevelEditor::Edit2 = SXGUICrEdit("0",80,460,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Edit2->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Edit2->SetColorText(0,0,0);
	SXLevelEditor::Edit2->SetColorTextBk(255,255,255);
	SXLevelEditor::Edit2->SetTransparentTextBk(true);
	SXLevelEditor::Edit2->SetColorBrush(255,255,255);
	SXLevelEditor::Edit3 = SXGUICrEdit("0",80,480,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Edit3->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Edit3->SetColorText(0,0,0);
	SXLevelEditor::Edit3->SetColorTextBk(255,255,255);
	SXLevelEditor::Edit3->SetTransparentTextBk(true);
	SXLevelEditor::Edit3->SetColorBrush(255,255,255);
	SXLevelEditor::Edit4 = SXGUICrEdit("0",80,500,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Edit4->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Edit4->SetColorText(0,0,0);
	SXLevelEditor::Edit4->SetColorTextBk(255,255,255);
	SXLevelEditor::Edit4->SetTransparentTextBk(true);
	SXLevelEditor::Edit4->SetColorBrush(255,255,255);
	SXLevelEditor::Button6 = SXGUICrButton("...",285,480,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button6->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button7 = SXGUICrButton("...",285,460,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button8 = SXGUICrButton("...",285,500,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button8->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Button9 = SXGUICrButton("...",285,520,25,15,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Button9->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static7 = SXGUICrStatic("Mask texture",5,520,70,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Static7->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Static7->SetColorText(0,0,0);
	SXLevelEditor::Static7->SetColorTextBk(255,255,255);
	SXLevelEditor::Static7->SetTransparentTextBk(true);
	SXLevelEditor::Static7->SetColorBrush(255,255,255);
	SXLevelEditor::Edit5 = SXGUICrEdit("0",80,520,200,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::Edit5->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::Edit5->SetColorText(0,0,0);
	SXLevelEditor::Edit5->SetColorTextBk(255,255,255);
	SXLevelEditor::Edit5->SetTransparentTextBk(true);
	SXLevelEditor::Edit5->SetColorBrush(255,255,255);
	SXLevelEditor::StatusBar1 = SXGUICrStatusBar("StatusBar1",SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StatusBar1->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::TrackBarDinsity = SXGUICrTrackBar("",330,460,200,20,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGenerate = SXGUICrButton("Generate",380,495,100,40,0,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::ButtonGenerate->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticDensityText = SXGUICrStatic("Density:",380,440,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticDensityText->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticDensityText->SetColorText(0,0,0);
	SXLevelEditor::StaticDensityText->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticDensityText->SetTransparentTextBk(true);
	SXLevelEditor::StaticDensityText->SetColorBrush(255,255,255);
	SXLevelEditor::StaticDensityVal = SXGUICrStatic("0",430,440,50,15,SXLevelEditor::JobWindow->GetHWND(),0,0);
	SXLevelEditor::StaticDensityVal->SetFont("MS Shell Dlg",-11,0,400,0,0,0);
	SXLevelEditor::StaticDensityVal->SetColorText(0,0,0);
	SXLevelEditor::StaticDensityVal->SetColorTextBk(255,255,255);
	SXLevelEditor::StaticDensityVal->SetTransparentTextBk(true);
	SXLevelEditor::StaticDensityVal->SetColorBrush(255,255,255);
}
void SXLevelEditor::DeleteAllElements()
{
	mem_delete(SXLevelEditor::RenderWindow);
	mem_delete(SXLevelEditor::ToolBar1);
	mem_delete(SXLevelEditor::GroupBoxList);
	mem_delete(SXLevelEditor::GroupBoxData);
	mem_delete(SXLevelEditor::ListBoxList);
	mem_delete(SXLevelEditor::StaticListTextCount);
	mem_delete(SXLevelEditor::StaticListValCount);
	mem_delete(SXLevelEditor::ButtonGeometryOpen);
	mem_delete(SXLevelEditor::ButtonGreenOpen);
	mem_delete(SXLevelEditor::ButtonLightOpen);
	mem_delete(SXLevelEditor::Button4);
	mem_delete(SXLevelEditor::Button5);
	mem_delete(SXLevelEditor::Static3);
	mem_delete(SXLevelEditor::Static4);
	mem_delete(SXLevelEditor::Static5);
	mem_delete(SXLevelEditor::Static6);
	mem_delete(SXLevelEditor::Edit1);
	mem_delete(SXLevelEditor::Edit2);
	mem_delete(SXLevelEditor::Edit3);
	mem_delete(SXLevelEditor::Edit4);
	mem_delete(SXLevelEditor::Button6);
	mem_delete(SXLevelEditor::Button7);
	mem_delete(SXLevelEditor::Button8);
	mem_delete(SXLevelEditor::Button9);
	mem_delete(SXLevelEditor::Static7);
	mem_delete(SXLevelEditor::Edit5);
	mem_delete(SXLevelEditor::StatusBar1);
	mem_delete(SXLevelEditor::TrackBarDinsity);
	mem_delete(SXLevelEditor::ButtonGenerate);
	mem_delete(SXLevelEditor::StaticDensityText);
	mem_delete(SXLevelEditor::StaticDensityVal);
	mem_delete(SXLevelEditor::JobWindow);
}
