#ifndef _GLPFN_H_
#define _GLPFN_H_

#if defined(_WINDOWS)
#	define WIN32_LEAN_AND_MEAN
#	include <Windows.h>
#endif

#include <gl/GL.h>
//#define GL_GLEXT_PROTOTYPES
#include <gl/glext.h>

#if defined(_LINUX) || defined(_MAC)
#	include <GL/glx.h>
#elif defined(_WINDOWS)
#	include <gl/wglext.h>
#endif

class IDSRGLPFN
{
public:
	IDSRGLPFN();

	PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT = NULL;

	PFNGLGENBUFFERSPROC glGenBuffers = NULL;
	PFNGLBINDBUFFERPROC glBindBuffer = NULL;
	PFNGLBUFFERDATAPROC glBufferData = NULL;
	PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;

	PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = NULL;
	PFNGLBINDVERTEXARRAYPROC glBindVertexArray = NULL;
	PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = NULL;

	PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
	PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;

	PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex = NULL;
	PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = NULL;

	PFNGLCREATESHADERPROC glCreateShader = NULL;//
	PFNGLSHADERSOURCEPROC glShaderSource = NULL;//
	PFNGLCOMPILESHADERPROC glCompileShader = NULL;//
	PFNGLDELETESHADERPROC glDeleteShader = NULL;//
	PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;//

//	PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv = NULL;
//	PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines = NULL;
//	PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines = NULL;
//	PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline = NULL;
//	PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages = NULL;
	PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramiv = NULL;
	PFNGLGETPROGRAMBINARYPROC glGetProgramBinary = NULL;
	PFNGLPROGRAMBINARYPROC glProgramBinary = NULL;
	PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
	//PFNGLPROGRAMPARAMETERPROC glProgramParameter

	PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;//
	PFNGLATTACHSHADERPROC glAttachShader = NULL;//
	PFNGLDETACHSHADERPROC glDetachShader = NULL;//
	PFNGLLINKPROGRAMPROC glLinkProgram = NULL;//
	PFNGLUSEPROGRAMPROC glUseProgram = NULL;//

	PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
	PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
};

#endif
